### ISSUE TITLE
All ballots should have the same size, pre-determined according to the election format

### ISSUE THREAD

**Issue by emduc** [dedis/d-voting#14]
If some ballots are encoded with more chunks of 29 bytes than others, then we could possibly map decrypted ballots to users. They should all have the same size, determined before hand, before the ballot is submitted to the chain

**Comment by nkcr** [comment]
To do that we must first support flexible election structures, instead of just a single list of candidates. You can check the format we though of there: https://github.com/dedis/d-voting/blob/main/docs/state%20of%20smart%20contract.md

You can see that the maximum ballot size can be computed with the `Configuration` of the election, since it contains all the questions.
