### ISSUE TITLE
Tests: Local tests

### ISSUE THREAD

**Issue by PascalinDe** [dedis/d-voting#335]
* [ ] 4+ nodes, randomly shutting down up to `f = (n - 1) / 3` nodes / restarting nodes
    * [ ] create form
    * [ ] cast votes
    * [ ] finalize election  
* [ ] test 100 elections with 2000 votes each
  * [ ] draw a figure with the medium time to response over the 200k votes
  * [ ] stress-test with many simultaneous votes (in practice probably not more than 10 votes / minute)
* [x] for each form of election (rank, select, text)
    * [x] create form
    * [x] cast votes
    * [x] finalize election

**Comment by PascalinDe** [comment]
@ineiti , @lanterno , @pierluca feel free to add test cases!

**Comment by pierluca** [comment]
> 4+ nodes was tested by DEDIS a while back.
This was broken a while back, should have been fixed since [this](https://github.com/dedis/dela/pull/215/files). Let me know how it goes.

Re: "100 elections with 2000 votes each"
Related fixes have happened [here](https://github.com/dedis/dela/issues/238) and [there](https://github.com/dedis/dela/pull/239).
One of the performance bottlenecks, if not the main one, is going to be [this](https://github.com/dedis/dela/issues/148) (i.e., not having implemented multi-level skipchain links).

**Comment by PascalinDe** [comment]
closing this to replace w/ more precise tickets
